Pull Request - LLD Port to Patmos
t-crest/patmos-llvm-project pull request #4
Opened 2022-03-15 12:18 UTC by haraldschn

This PR request includes changes to use LLD (instead of Gold) for Linking.

The main changes in this PR are:

- Added `patmos.cpp` (and class Patmos) to LLD with Implementation for the Relocation Types
- Changes in LLD-Code `Driver.cpp, InputFiles.cpp, ScriptParser.cpp, Target.cpp and Target.h` to include Patmos
- Adaption of Clang and LLVM Testcases to use `ld.lld` instead of `patmos-ld` (Gold-Linker)
- Adaption of Clang to call LLD instead of the Gold-Linker.
- Add Information in `README-Patmos` for the testing of LLD and adaptions to include LLD during a Build
- Add Packaging of `ld.lld` and `lld` within `llvm/cmake/platforms/Patmos.cmake`

2022-03-16 10:18 UTC, Emoun commented on .github/actions/build-test-all/action.yml
> +        targets: UnitTests FileCheck count not lli llvm-strip llvm-install-name-tool dsymutil lli-child-target llvm-as llvm-bcanalyzer llvm-config llvm-cov llvm-cxxdump llvm-cvtres llvm-diff llvm-dis
There is no need to build targets twice, so we can remove any target that was built as part of the LLD tests in line 82

2022-03-16 10:20 UTC, Emoun commented on README-Patmos.MD
> +git sparse-checkout add /.github /llvm /clang /compiler-rt /lld /libunwind
what is `libunwind`? does it not work without it?

2022-03-16 10:25 UTC, Emoun commented on clang/lib/Driver/ToolChains/Patmos.cpp
> +  // Set LLD Option: Optimize output file to 0, to prevent LLD from unwanted changes in the Outputfile.
```suggestion
  // String merging seems to also change data saved as floats or doubles. Disable it to avoid the unwanted changes.
```

2022-03-16 10:27 UTC, Emoun commented on clang/lib/Driver/ToolChains/Patmos.cpp
> +  return(get_patmos_tool(TC, "ld.lld"));
We need LLD to be prefixed by `patmos-`,  so that it doesn't clash with a regular installation of LLVM that a user might have. 
```suggestion
  return(get_patmos_tool(TC, "patmos-ld.lld"));
```

2022-03-16 10:33 UTC, Emoun commented on clang/test/Driver/Patmos/default-patmos-lld.c
> +// CHECK: ld.lld: error: unknown argument '--bogus-patmos-lld-flag'
I think this whole test is not needed, as the linker is not an external tool any more. I would say just delete it.

2022-03-16 10:38 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ABS32.s
> +// REQUIRES: patmos
Instead of having `REQUIRES: patmos` in every file, try looking at `clang/test/Driver/Patmos/lit.local`. The first line there will do the same for all the files in the folder at once. Then you shouldn't need this line in every test file

2022-03-16 10:38 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ABS32.s
> +// ?????:   S = 0x100, A = 0xfffffeff
What does `?????:` do here?

2022-03-16 10:45 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ABS32_xfail.s
> +// RUN: ld.lld %t.o %t257.o -o /dev/null 2>&1
If you are expecting an error here, maybe it is useful to check that the right error is thrown. Look at `clang/test/Driver/Patmos/invalid-env-var-patmos-gold.c` for how to check for failures without using `XFAIL`

2022-03-16 10:47 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ALU-ABS.s
> +# RUN: ld.lld %t.patmos.o --defsym foo=4095 -o %t2.o
I would prefer that all `RUN` commands are at the beginning of the file so that it is easy to see what tests are run without having to check the rest of the file for more commands. 
Should also use the `END` command for efficiency.

2022-03-16 10:49 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ALUI-ABS_xfail.s
> +# XFAIL: *
Same as `patmos-ABS32_xfail.s` regarding testing errors.

2022-03-16 10:49 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-ALUL-ABS_xfail.s
> +# XFAIL: *
Same as `patmos-ABS32_xfail.s` regarding testing errors.

2022-03-16 10:51 UTC, Emoun commented on lld/test/ELF/Patmos/patmos-CFLI-ABS-callnd.s
> +# RUN: ld.lld %t.patmos.o --defsym foo=16777215 --defsym bar=8 -o %t2
Same as `patmos-ALU-ABS.s` regarding positioning of commands.

2022-03-16 10:58 UTC, Emoun requested changes
@haraldschn thanks a lot for this PR. Very nice work.

I have added comments here and there that I would ask you to look at.

2022-03-16 13:56 UTC, haraldschn commented on README-Patmos.MD
> +git sparse-checkout add /.github /llvm /clang /compiler-rt /lld /libunwind
Without checking out `libunwind` this version of lld cannot be built locally.
The Files `lld/MachO/UnwindInfoSection.cpp` and `lld/MachO/Writer.cpp` include files from `libunwind` at build time. 

(I didn't really want to change anything within the MachO implemenation in LLD, 
the Linker port only depends on the ELF Implementation in LLD.)

2022-03-16 13:58 UTC, haraldschn commented on .github/actions/build-test-all/action.yml
> +        targets: UnitTests FileCheck count not lli llvm-strip llvm-install-name-tool dsymutil lli-child-target llvm-as llvm-bcanalyzer llvm-config llvm-cov llvm-cxxdump llvm-cvtres llvm-diff llvm-dis
I have removed duplicate target in line 90

2022-03-16 14:01 UTC, haraldschn commented on .github/actions/build-test-all/action.yml
> +        targets: UnitTests FileCheck count not lli llvm-strip llvm-install-name-tool dsymutil lli-child-target llvm-as llvm-bcanalyzer llvm-config llvm-cov llvm-cxxdump llvm-cvtres llvm-diff llvm-dis
Duplicate targets are now removed from line 90

2022-03-16 14:04 UTC, haraldschn commented on clang/lib/Driver/ToolChains/Patmos.cpp
> +  // Set LLD Option: Optimize output file to 0, to prevent LLD from unwanted changes in the Outputfile.
I included the change of the comment in f20af8ed9b79f4cd1ced5b5949be0d70d0ae758a

2022-03-16 14:05 UTC, haraldschn commented on clang/test/Driver/Patmos/default-patmos-lld.c
> +// CHECK: ld.lld: error: unknown argument '--bogus-patmos-lld-flag'
This testcase is deleted in f20af8ed9b79f4cd1ced5b5949be0d70d0ae758a

2022-03-16 14:09 UTC, haraldschn commented on lld/test/ELF/Patmos/patmos-ABS32.s
> +// REQUIRES: patmos
The `REQUIRES: patmos` is now deleted in all Patmos specific testcases and replaced with a `lld/test/ELF/Patmos/lit.local.cfg` f20af8ed9b79f4cd1ced5b5949be0d70d0ae758a to only run test when Patmos is available.

2022-03-16 14:23 UTC, haraldschn commented on lld/test/ELF/Patmos/patmos-ABS32_xfail.s
> +// RUN: ld.lld %t.o %t257.o -o /dev/null 2>&1
In commit f20af8ed9b79f4cd1ced5b5949be0d70d0ae758a if changed all `XFAIL` checks to checks of the according errors.

To highlight the difference from the 'XFAIL' checks,
I've changed the names of these testcases from `*_xfail.s` to `*_error.s`

2022-03-16 14:24 UTC, haraldschn commented on lld/test/ELF/Patmos/patmos-ALU-ABS.s
> +# RUN: ld.lld %t.patmos.o --defsym foo=4095 -o %t2.o
The `RUN` commands are with commit f20af8ed9b79f4cd1ced5b5949be0d70d0ae758a all at the beginning of the file.

2022-03-17 10:14 UTC, Emoun commented on README-Patmos.MD
> +git sparse-checkout add /.github /llvm /clang /compiler-rt /lld /libunwind
Ok, yes it is probably best to not mess with other code needlessly

2022-03-17 10:26 UTC, Emoun approved these changes
@haraldschn thanks for the changes, everything looks good. I'll get the CI running
and if everything seems good there I think we can merge it.

2022-03-18 08:55 UTC, Emoun commented
@haraldschn it seems adding lld to the build has made come quite close to the default build timeout of 6 hours. To make sure that it has enough time, I suggest we increase the timeout to 7 hours. Can I get you to do that using `timeout-minutes` for all jobs?

2022-03-18 09:28 UTC, haraldschn commented
@Emoun is it possible to increase the timeout-minutes beyond 6 hours (without using a self-hosted runner) ?

Under "Usage Limits" https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits a maximum of 6 hours for each job is stated.

I found a discussion on github for jobs.<job_id>.timeout-minutes description is misleading https://github.com/github/docs/issues/7984

2022-03-18 10:15 UTC, Emoun commented
Yes, it seems you are right. Never mind then, I'll merge this as-is.
Later I will remove the `Test-Build Newlib` step to win us some time, since it is only there as a sanity check.

2022-03-18 10:20 UTC, merged